services:
  invasionview:
    build: .
    container_name: invasionview
    environment:
      - QT_QPA_PLATFORM=wayland
      - XDG_RUNTIME_DIR=/tmp/xdg
    volumes:
      - /run/user/1000/wayland-0:/tmp/xdg/wayland-0
      - ./src:/app/src
    stdin_open: true
    tty: true
    command: /app/build_and_run.sh

