services:
  invasionview:
    build: .
    container_name: invasionview
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
      - XDG_RUNTIME_DIR=/tmp/xdg
      - TZ=Europe/Berlin
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/app/src
      - ./include:/app/include
      - ./qml:/app/qml
      - ./data:/app/data
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true
