# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/timon/DesktopInvasion

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/timon/DesktopInvasion

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timon/DesktopInvasion/CMakeFiles /home/timon/DesktopInvasion//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timon/DesktopInvasion/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/timon/DesktopInvasion/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DesktopInvasion

# Build rule for target.
DesktopInvasion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DesktopInvasion
.PHONY : DesktopInvasion

# fast build rule for target.
DesktopInvasion/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/build
.PHONY : DesktopInvasion/fast

#=============================================================================
# Target rules for targets named DesktopInvasion_autogen_timestamp_deps

# Build rule for target.
DesktopInvasion_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DesktopInvasion_autogen_timestamp_deps
.PHONY : DesktopInvasion_autogen_timestamp_deps

# fast build rule for target.
DesktopInvasion_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion_autogen_timestamp_deps.dir/build.make CMakeFiles/DesktopInvasion_autogen_timestamp_deps.dir/build
.PHONY : DesktopInvasion_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named DesktopInvasion_autogen

# Build rule for target.
DesktopInvasion_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DesktopInvasion_autogen
.PHONY : DesktopInvasion_autogen

# fast build rule for target.
DesktopInvasion_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion_autogen.dir/build.make CMakeFiles/DesktopInvasion_autogen.dir/build
.PHONY : DesktopInvasion_autogen/fast

DesktopInvasion_autogen/mocs_compilation.o: DesktopInvasion_autogen/mocs_compilation.cpp.o
.PHONY : DesktopInvasion_autogen/mocs_compilation.o

# target to build an object file
DesktopInvasion_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/DesktopInvasion_autogen/mocs_compilation.cpp.o
.PHONY : DesktopInvasion_autogen/mocs_compilation.cpp.o

DesktopInvasion_autogen/mocs_compilation.i: DesktopInvasion_autogen/mocs_compilation.cpp.i
.PHONY : DesktopInvasion_autogen/mocs_compilation.i

# target to preprocess a source file
DesktopInvasion_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/DesktopInvasion_autogen/mocs_compilation.cpp.i
.PHONY : DesktopInvasion_autogen/mocs_compilation.cpp.i

DesktopInvasion_autogen/mocs_compilation.s: DesktopInvasion_autogen/mocs_compilation.cpp.s
.PHONY : DesktopInvasion_autogen/mocs_compilation.s

# target to generate assembly for a file
DesktopInvasion_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/DesktopInvasion_autogen/mocs_compilation.cpp.s
.PHONY : DesktopInvasion_autogen/mocs_compilation.cpp.s

# target to build an object file
cmake_pch.hxx.gch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/cmake_pch.hxx.gch
.PHONY : cmake_pch.hxx.gch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

qrc_resources.o: qrc_resources.cpp.o
.PHONY : qrc_resources.o

# target to build an object file
qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/qrc_resources.cpp.o
.PHONY : qrc_resources.cpp.o

qrc_resources.i: qrc_resources.cpp.i
.PHONY : qrc_resources.i

# target to preprocess a source file
qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/qrc_resources.cpp.i
.PHONY : qrc_resources.cpp.i

qrc_resources.s: qrc_resources.cpp.s
.PHONY : qrc_resources.s

# target to generate assembly for a file
qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/qrc_resources.cpp.s
.PHONY : qrc_resources.cpp.s

src/Battle.o: src/Battle.cpp.o
.PHONY : src/Battle.o

# target to build an object file
src/Battle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/Battle.cpp.o
.PHONY : src/Battle.cpp.o

src/Battle.i: src/Battle.cpp.i
.PHONY : src/Battle.i

# target to preprocess a source file
src/Battle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/Battle.cpp.i
.PHONY : src/Battle.cpp.i

src/Battle.s: src/Battle.cpp.s
.PHONY : src/Battle.s

# target to generate assembly for a file
src/Battle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/Battle.cpp.s
.PHONY : src/Battle.cpp.s

src/BattleMoveHandler.o: src/BattleMoveHandler.cpp.o
.PHONY : src/BattleMoveHandler.o

# target to build an object file
src/BattleMoveHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/BattleMoveHandler.cpp.o
.PHONY : src/BattleMoveHandler.cpp.o

src/BattleMoveHandler.i: src/BattleMoveHandler.cpp.i
.PHONY : src/BattleMoveHandler.i

# target to preprocess a source file
src/BattleMoveHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/BattleMoveHandler.cpp.i
.PHONY : src/BattleMoveHandler.cpp.i

src/BattleMoveHandler.s: src/BattleMoveHandler.cpp.s
.PHONY : src/BattleMoveHandler.s

# target to generate assembly for a file
src/BattleMoveHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/BattleMoveHandler.cpp.s
.PHONY : src/BattleMoveHandler.cpp.s

src/DesktopScene.o: src/DesktopScene.cpp.o
.PHONY : src/DesktopScene.o

# target to build an object file
src/DesktopScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/DesktopScene.cpp.o
.PHONY : src/DesktopScene.cpp.o

src/DesktopScene.i: src/DesktopScene.cpp.i
.PHONY : src/DesktopScene.i

# target to preprocess a source file
src/DesktopScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/DesktopScene.cpp.i
.PHONY : src/DesktopScene.cpp.i

src/DesktopScene.s: src/DesktopScene.cpp.s
.PHONY : src/DesktopScene.s

# target to generate assembly for a file
src/DesktopScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/DesktopScene.cpp.s
.PHONY : src/DesktopScene.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameMenu.o: src/GameMenu.cpp.o
.PHONY : src/GameMenu.o

# target to build an object file
src/GameMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/GameMenu.cpp.o
.PHONY : src/GameMenu.cpp.o

src/GameMenu.i: src/GameMenu.cpp.i
.PHONY : src/GameMenu.i

# target to preprocess a source file
src/GameMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/GameMenu.cpp.i
.PHONY : src/GameMenu.cpp.i

src/GameMenu.s: src/GameMenu.cpp.s
.PHONY : src/GameMenu.s

# target to generate assembly for a file
src/GameMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/GameMenu.cpp.s
.PHONY : src/GameMenu.cpp.s

src/PokemonDatabase.o: src/PokemonDatabase.cpp.o
.PHONY : src/PokemonDatabase.o

# target to build an object file
src/PokemonDatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/PokemonDatabase.cpp.o
.PHONY : src/PokemonDatabase.cpp.o

src/PokemonDatabase.i: src/PokemonDatabase.cpp.i
.PHONY : src/PokemonDatabase.i

# target to preprocess a source file
src/PokemonDatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/PokemonDatabase.cpp.i
.PHONY : src/PokemonDatabase.cpp.i

src/PokemonDatabase.s: src/PokemonDatabase.cpp.s
.PHONY : src/PokemonDatabase.s

# target to generate assembly for a file
src/PokemonDatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/PokemonDatabase.cpp.s
.PHONY : src/PokemonDatabase.cpp.s

src/SystemTrayIcon.o: src/SystemTrayIcon.cpp.o
.PHONY : src/SystemTrayIcon.o

# target to build an object file
src/SystemTrayIcon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/SystemTrayIcon.cpp.o
.PHONY : src/SystemTrayIcon.cpp.o

src/SystemTrayIcon.i: src/SystemTrayIcon.cpp.i
.PHONY : src/SystemTrayIcon.i

# target to preprocess a source file
src/SystemTrayIcon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/SystemTrayIcon.cpp.i
.PHONY : src/SystemTrayIcon.cpp.i

src/SystemTrayIcon.s: src/SystemTrayIcon.cpp.s
.PHONY : src/SystemTrayIcon.s

# target to generate assembly for a file
src/SystemTrayIcon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/SystemTrayIcon.cpp.s
.PHONY : src/SystemTrayIcon.cpp.s

src/WildPokemon.o: src/WildPokemon.cpp.o
.PHONY : src/WildPokemon.o

# target to build an object file
src/WildPokemon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/WildPokemon.cpp.o
.PHONY : src/WildPokemon.cpp.o

src/WildPokemon.i: src/WildPokemon.cpp.i
.PHONY : src/WildPokemon.i

# target to preprocess a source file
src/WildPokemon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/WildPokemon.cpp.i
.PHONY : src/WildPokemon.cpp.i

src/WildPokemon.s: src/WildPokemon.cpp.s
.PHONY : src/WildPokemon.s

# target to generate assembly for a file
src/WildPokemon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/WildPokemon.cpp.s
.PHONY : src/WildPokemon.cpp.s

src/data_move.o: src/data_move.cpp.o
.PHONY : src/data_move.o

# target to build an object file
src/data_move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_move.cpp.o
.PHONY : src/data_move.cpp.o

src/data_move.i: src/data_move.cpp.i
.PHONY : src/data_move.i

# target to preprocess a source file
src/data_move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_move.cpp.i
.PHONY : src/data_move.cpp.i

src/data_move.s: src/data_move.cpp.s
.PHONY : src/data_move.s

# target to generate assembly for a file
src/data_move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_move.cpp.s
.PHONY : src/data_move.cpp.s

src/data_poke.o: src/data_poke.cpp.o
.PHONY : src/data_poke.o

# target to build an object file
src/data_poke.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_poke.cpp.o
.PHONY : src/data_poke.cpp.o

src/data_poke.i: src/data_poke.cpp.i
.PHONY : src/data_poke.i

# target to preprocess a source file
src/data_poke.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_poke.cpp.i
.PHONY : src/data_poke.cpp.i

src/data_poke.s: src/data_poke.cpp.s
.PHONY : src/data_poke.s

# target to generate assembly for a file
src/data_poke.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_poke.cpp.s
.PHONY : src/data_poke.cpp.s

src/data_poke_asset.o: src/data_poke_asset.cpp.o
.PHONY : src/data_poke_asset.o

# target to build an object file
src/data_poke_asset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_poke_asset.cpp.o
.PHONY : src/data_poke_asset.cpp.o

src/data_poke_asset.i: src/data_poke_asset.cpp.i
.PHONY : src/data_poke_asset.i

# target to preprocess a source file
src/data_poke_asset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_poke_asset.cpp.i
.PHONY : src/data_poke_asset.cpp.i

src/data_poke_asset.s: src/data_poke_asset.cpp.s
.PHONY : src/data_poke_asset.s

# target to generate assembly for a file
src/data_poke_asset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_poke_asset.cpp.s
.PHONY : src/data_poke_asset.cpp.s

src/data_poke_flavor.o: src/data_poke_flavor.cpp.o
.PHONY : src/data_poke_flavor.o

# target to build an object file
src/data_poke_flavor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_poke_flavor.cpp.o
.PHONY : src/data_poke_flavor.cpp.o

src/data_poke_flavor.i: src/data_poke_flavor.cpp.i
.PHONY : src/data_poke_flavor.i

# target to preprocess a source file
src/data_poke_flavor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_poke_flavor.cpp.i
.PHONY : src/data_poke_flavor.cpp.i

src/data_poke_flavor.s: src/data_poke_flavor.cpp.s
.PHONY : src/data_poke_flavor.s

# target to generate assembly for a file
src/data_poke_flavor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/data_poke_flavor.cpp.s
.PHONY : src/data_poke_flavor.cpp.s

src/globals.o: src/globals.cpp.o
.PHONY : src/globals.o

# target to build an object file
src/globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/globals.cpp.o
.PHONY : src/globals.cpp.o

src/globals.i: src/globals.cpp.i
.PHONY : src/globals.i

# target to preprocess a source file
src/globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/globals.cpp.i
.PHONY : src/globals.cpp.i

src/globals.s: src/globals.cpp.s
.PHONY : src/globals.s

# target to generate assembly for a file
src/globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/globals.cpp.s
.PHONY : src/globals.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tests.o: src/tests.cpp.o
.PHONY : src/tests.o

# target to build an object file
src/tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/tests.cpp.o
.PHONY : src/tests.cpp.o

src/tests.i: src/tests.cpp.i
.PHONY : src/tests.i

# target to preprocess a source file
src/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/tests.cpp.i
.PHONY : src/tests.cpp.i

src/tests.s: src/tests.cpp.s
.PHONY : src/tests.s

# target to generate assembly for a file
src/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesktopInvasion.dir/build.make CMakeFiles/DesktopInvasion.dir/src/tests.cpp.s
.PHONY : src/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DesktopInvasion_autogen"
	@echo "... DesktopInvasion_autogen_timestamp_deps"
	@echo "... DesktopInvasion"
	@echo "... DesktopInvasion_autogen/mocs_compilation.o"
	@echo "... DesktopInvasion_autogen/mocs_compilation.i"
	@echo "... DesktopInvasion_autogen/mocs_compilation.s"
	@echo "... cmake_pch.hxx.gch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
	@echo "... qrc_resources.o"
	@echo "... qrc_resources.i"
	@echo "... qrc_resources.s"
	@echo "... src/Battle.o"
	@echo "... src/Battle.i"
	@echo "... src/Battle.s"
	@echo "... src/BattleMoveHandler.o"
	@echo "... src/BattleMoveHandler.i"
	@echo "... src/BattleMoveHandler.s"
	@echo "... src/DesktopScene.o"
	@echo "... src/DesktopScene.i"
	@echo "... src/DesktopScene.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameMenu.o"
	@echo "... src/GameMenu.i"
	@echo "... src/GameMenu.s"
	@echo "... src/PokemonDatabase.o"
	@echo "... src/PokemonDatabase.i"
	@echo "... src/PokemonDatabase.s"
	@echo "... src/SystemTrayIcon.o"
	@echo "... src/SystemTrayIcon.i"
	@echo "... src/SystemTrayIcon.s"
	@echo "... src/WildPokemon.o"
	@echo "... src/WildPokemon.i"
	@echo "... src/WildPokemon.s"
	@echo "... src/data_move.o"
	@echo "... src/data_move.i"
	@echo "... src/data_move.s"
	@echo "... src/data_poke.o"
	@echo "... src/data_poke.i"
	@echo "... src/data_poke.s"
	@echo "... src/data_poke_asset.o"
	@echo "... src/data_poke_asset.i"
	@echo "... src/data_poke_asset.s"
	@echo "... src/data_poke_flavor.o"
	@echo "... src/data_poke_flavor.i"
	@echo "... src/data_poke_flavor.s"
	@echo "... src/globals.o"
	@echo "... src/globals.i"
	@echo "... src/globals.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tests.o"
	@echo "... src/tests.i"
	@echo "... src/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/timon/DesktopInvasion/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

